---
driver_plugin: vagrant

platforms:
- name: ubuntu-12.04
  driver_config:
    box: precise64
    box_url: http://files.vagrantup.com/precise64.box
    require_chef_omnibus: true
  run_list:
    - recipe[apt]

suites:
- name: default
  run_list:
    - recipe[minitest-handler]
    - recipe[logmetrics_test]
